### ISSUE TITLE
QA-CRM-Password Reset Page-Low-When user click on forget password link and application redirect in password reset page but page name is showing "Login In" in places of "Reset Password"

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/crmadmin-cum-finance#124]
When user click on forget password link and application redirect in password reset page but page name is showing "Login In" in places of "Reset Password"

**Comment by dweep119** [comment]
Please attach Screen Shot.

**Comment by qajha** [comment]
Issue is working fine in QA server
