### ISSUE TITLE
QA - CRM - Add New Customer - Low - Background color not saved after log out and login

### ISSUE THREAD

**Issue by brgurur** [FlowzPlatform/crmadmin-cum-finance#129]
When i try to add a new customer and the background color i have changed and the font color also changed and after log out and login i am unable to see the changes.

![color](https://user-images.githubusercontent.com/34448885/36199934-15d7b444-11a1-11e8-8724-fb6916f4d864.jpg)

**Comment by npaulOB** [comment]
@kdalsania Could you please remove the vue-widget from here and use simple card Designs.

**Comment by brgurur** [comment]
Panel was changed, so color or font changes will not exists.
