### ISSUE TITLE
QA-CRM-High-When user select the Vmail option from flowz-product option then system is redirect in new URL but application is not open.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/crmadmin-cum-finance#138]
When user selects the Vmail option from flowz-product option then the system is redirected in new URL but application is not open.
![vmail option](https://user-images.githubusercontent.com/36195435/36294659-3b58ceca-1308-11e8-981f-100fc147eef4.png)

**Comment by npaulOB** [comment]
As vmail is not listed in this release , I will remove that link from CRM .

**Comment by npaulOB** [comment]
As par the discussion with @chiragob, Vmail will be live shortly, Thus I am not changing anything. It will open the application ASA it is live.

**Comment by npaulOB** [comment]
As par discussion with team and @chiragob we will change the vmail link to v-shop data

**Comment by qajha** [comment]
Issue is resolved now in QA server
