### ISSUE TITLE
QA-CRM-When user select the any plan for user plan dropdown list then system is showing only selected plan invite details in Invite Subscription Tab only not all plans invite user details.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/crmadmin-cum-finance#153]
When user select the any plan for user plan dropdown list then system is showing only selected plan invite details in Invite Subscription Tab only not all plans invite user details.

**Comment by npaulOB** [comment]
This is not an issue as the invite section is not filtered with the selected subscription plan. This is the place where the admin comes and manipulate/ manage all his subscriptions and assignees.So you can close the issue

**Comment by qajha** [comment]
Closed as per mention comment by Dev
