### ISSUE TITLE
QA-CRM-Trnsaction List-When user pay the full payment for ordered but system is updated the wrong ordered amount in Transaction list 

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/crmadmin-cum-finance#193]
When user pay the full payment for ordered but system is updated the wrong ordered amount in Transaction list

**Comment by npaulOB** [comment]
From website end, it should send the correct amount. currently its static ($400) in website end. No need to change anything in CRM module.

**Comment by qajha** [comment]
Issue is resolved now in QA server
