### ISSUE TITLE
QA-CRM-Order List-VIEW ORDER DETAILS-Paid amont and Due amount is showing wrong actually client is paid the full amount in ordered time.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/crmadmin-cum-finance#197]
Paid amont and Due amount is showing wrong actually client is paid the full amount in ordered time.
![paid amount](https://user-images.githubusercontent.com/36195435/36779420-ec9fed80-1c95-11e8-914e-7ae825130eaa.png)

**Comment by npaulOB** [comment]
From website end, it should send the correct amount. currently its static ($400) in website end. No need to change anything in CRM module.

**Comment by qajha** [comment]
Issue is resolved now in QA server
