### ISSUE TITLE
QA-Invoice List-Payment section-When user click on pay button multiple times system is showing Error Refer attachment

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/crmadmin-cum-finance#226]
![invoice list payment option](https://user-images.githubusercontent.com/36195435/37094164-e9dacfe6-2237-11e8-9e34-18c3cc033881.png)

**Comment by npaulOB** [comment]
This issue is solved. Though If you try to pay with PayPal you will get an error as we don't have correct paypal credentials

**Comment by qajha** [comment]
Issue is resolved now in QA server
