### ISSUE TITLE
QA-CRM-Dashbaord-In Invoice amount section if user click on Draft amount option then system is showing the Draft amount text is overlap.Refer attachment

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/crmadmin-cum-finance#242]
![invoice amount](https://user-images.githubusercontent.com/36195435/37330302-a7d01456-26c6-11e8-969b-a16afe0b79f9.png)

**Comment by qajha** [comment]
![still overlap data draft amount](https://user-images.githubusercontent.com/36195435/38018394-6dd21088-3292-11e8-8f2b-a34c9b741e94.png)

**Comment by qajha** [comment]
![still overlap data draft amount](https://user-images.githubusercontent.com/36195435/38018421-797e6fee-3292-11e8-9f23-66f23b748c82.png)

**Comment by qajha** [comment]
Still problem is not resolved yet.

**Comment by npaulOB** [comment]
This issue will arise if the user clicks on the chart. There is not much we can do as the chart is auto-generated.You can close the issue
