### ISSUE TITLE
QA-CRM-Admin Account-Request Info-The product name is not displaying properly in request info screen in CRM.Refer Attachment

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/crmadmin-cum-finance#254]
### For Issue creation, please use below template and remove above template.
--------------------

### Issue Summary:
The product name is not displaying properly on request info screen in CRM.Refer Attachment

### Prerequisite:
-Product information should be shown properly on  Request Info screen.
### Issue Reproduce Steps:
    1.Login into CRM Application
    2.Go to admin Account>Request Info tab
    
### Expected Result:
    1.The product name should be showing properly.
 
### Actual Result:
    1. The product name is not showing properly in 
    
### Environment Details
    - Windows desktop OS
    - Windows Server OS
    - Linux

![request info product name](https://user-images.githubusercontent.com/36195435/37388167-5e10f3a2-2785-11e8-809f-de06b8c569d0.png)

**Comment by Nikunj025** [comment]
Done
