### ISSUE TITLE
QA-CRM-Admin Account-Request Quote-In request quote the Total Item and color wise quantity total is showing wrong 

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/crmadmin-cum-finance#264]
![total items and total](https://user-images.githubusercontent.com/36195435/37393626-91e3fd48-2797-11e8-8c1f-7a6deb356604.png)

**Comment by npaulOB** [comment]
Has dependency on website end

**Comment by qajha** [comment]
Issue is resolved in QA server
