### ISSUE TITLE
QA - CRM - Request Info - Remove Black Dot After Qty in Price Grid.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/crmadmin-cum-finance#279]
QA - CRM - Request Info - Remove Black Dot After Qty in Price Grid.

Also Need Proper UI Of Label Qty And Price Column in CRM.

![remove black dot after qty in price grid](https://user-images.githubusercontent.com/36226408/37769290-8dc0062a-2df6-11e8-8431-b506cd31a010.jpg)

**Comment by qajha** [comment]
Issue is resolved now in QA server
