### ISSUE TITLE
QA - CRM - Request Info - Pricing Should be display in Two Decimal.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/crmadmin-cum-finance#280]
QA - CRM - Request Info - Pricing Should be display in Two Decimal.

![pricing should be display in two decimal](https://user-images.githubusercontent.com/36226408/37769397-ddf5b586-2df6-11e8-955a-7e5e5c96398b.jpg)

**Comment by qajha** [comment]
Issue is resolved now in QA server
