### ISSUE TITLE
QA - CRM - Need to Display Favicon icon for CRM in Browser Tab.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/crmadmin-cum-finance#290]
QA - CRM - Need to Display Favicon icon for CRM in Browser Tab.

For Favicon icon refer Flowz Builder.

![need to display favicon icon for crm in browser tab](https://user-images.githubusercontent.com/36226408/37900199-29ecef4c-310b-11e8-8d05-e1b8ddda201b.jpg)

**Comment by qajha** [comment]
Issue is resolved now in QA server
