### ISSUE TITLE
QA-CRM-In Request Info filter by product Name and Name data is showing multiple times in dropdown list.Refer attacment

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/crmadmin-cum-finance#295]
![request info](https://user-images.githubusercontent.com/36195435/37905239-d8bad6dc-311b-11e8-98b6-ca92f6be22a2.png)

**Comment by npaulOB** [comment]
Couldn't able to reproduce the issue. Working fine for the same user in QA.referred Attachments.
![alll](https://user-images.githubusercontent.com/32832534/38025279-657f3664-32a5-11e8-91c2-8d678c7972f2.png)

**Comment by npaulOB** [comment]
Couldn't reproduce the issue for same user in QA. PFA.
![alll](https://user-images.githubusercontent.com/32832534/38025315-8cb78b28-32a5-11e8-91d1-031b99d3ceaf.png)

**Comment by qajha** [comment]
Issue is resolved now in QA server
