### ISSUE TITLE
QA-CRM-Suggestion-Request Info and Request Quote and Order List page need to be configure some things different look and feel for the customer point of view.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/crmadmin-cum-finance#296]
QA-CRM-Suggestion-Request Info and Request Quote and Order List page need to be configure some things different look and feel for the customer point of view. #296

Test Scenarios
***************
1. UI Should be Different for All Pages.
2. As User Point of View, All the things should have different Design for Listing, So User can easily identify that they are Access which Page.

**Comment by dweep119** [comment]
We change the UI of request quote and request info.

**Comment by Nikunj025** [comment]
Done
