### ISSUE TITLE
QA-CRM-Dashboard-In Amount paid cash flow the NaN.undefined value is showing.Refer attachment

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/crmadmin-cum-finance#313]
![screenshot from 2018-03-28 14-07-30](https://user-images.githubusercontent.com/36195435/38018100-93244776-3291-11e8-9489-21bee5925b89.png)

**Comment by npaulOB** [comment]
This is an old build as there is no username box in the header at the left of subscription drop-down.

**Comment by qajha** [comment]
Issue is resolved now in QA server
