### ISSUE TITLE
Numbers in table should always be right aligned

### ISSUE THREAD

**Issue by npaulOB** [FlowzPlatform/crmadmin-cum-finance#315]
@npaulOB commented on [Wed Mar 28 2018](https://github.com/FlowzPlatform/Sprint-User-Story-Board/issues/60)

### SUMMARY:
----
### Prerequisite:
-Functionality must be working.

### User Story Description:
    As a <customer>, i need a <contact us component> so that i can easily drag and build contact us page.

### Acceptance Criteria:
1. Business Use case - 1
2. Business Use case - 2
 
###  Environment Applicable:

- Windows desktop OS
- Windows Server OS
- Linux

### Issue Summary:
----
### Prerequisite:
-Functionality must be working.

### Issue Reproduce Steps:
    1.Open URL.
    2. 
    
### Expected Result:
    1.Component should work
 
### Actual Result:
    1. Component is not working.
    
### Environment Details
    - Windows desktop OS
    - Windows Server OS
    - Linux

**Comment by qajha** [comment]
Done
