### ISSUE TITLE
Create new API to support add payment gateway feature from webbuilder

### ISSUE THREAD

**Issue by npaulOB** [FlowzPlatform/crmadmin-cum-finance#317]
### SUMMARY: Create new API to support add payment gateway feature from webbuilder
----
### Prerequisite:
-Functionality must be working.

### User Story Description:
    As a <customer>, i need a <contact us component> so that i can easily drag and build contact us page.

### Acceptance Criteria:
1. Business Use case - 1
2. Business Use case - 2
 
###  Environment Applicable:

- Windows desktop OS
- Windows Server OS
- Linux

**Comment by kdalsania** [comment]
done
