### ISSUE TITLE
QA-CRM-When user login into CRM then system is showing popup window for "Go for Setting"  but those setting is already created for that user .

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/crmadmin-cum-finance#320]
![setting save](https://user-images.githubusercontent.com/36195435/38074304-f6b537b8-334b-11e8-823a-c3ff48a1cd5a.png)

Test Scenarios
***************
1. Popup should be display first time after login.
2. If User have already create Setting then Create Setting popup should not be display.

**Comment by Nikunj025** [comment]
Done.
