### ISSUE TITLE
QA-CRM-Invoice List-System is not showing any successfull message for "Email is send successfully".

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/crmadmin-cum-finance#321]
1.The system is not showing any successful message for "Email is sent successfully".
2.Due Date is showing the current date in customer received an email invoice.

**Comment by npaulOB** [comment]
If the due date is not specified while creating an order, It will show the current date. This is expected behavior.But if it is specified, system will show that particular date

**Comment by kdalsania** [comment]
solved
