### ISSUE TITLE
QA-CRM-Admin Account-Order List-When user change the plan but not website is linked then system is showing Error message Refer Attachment

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/crmadmin-cum-finance#323]
![order list](https://user-images.githubusercontent.com/36195435/38087822-2f068786-3377-11e8-9187-75f222829a29.png)

**Comment by npaulOB** [comment]
It is solved. For the new subscriptions, it will show "website is not available for this subscription"

**Comment by kdalsania** [comment]
solved
