### ISSUE TITLE
Chat between customer and end user in request Quote and request Info

### ISSUE THREAD

**Issue by npaulOB** [FlowzPlatform/crmadmin-cum-finance#326]
### SUMMARY:
----
### Prerequisite:
-Functionality must be working.

### User Story Description:
    As an <Admin>, I need to <see and chat with> end users so that I can easily understand their Queries.

### Acceptance Criteria:
1. Chat should be real-time
2. should be requested ID specific

**Comment by kdalsania** [comment]
done
