### ISSUE TITLE
junk characters

### ISSUE THREAD

**Issue by emp005169** [FlowzPlatform/crmadmin-cum-finance#36]
in new customer -> configuration name.
in list customer -> no data
in new relationship -> status, assignee, status, product line
in list relationship -> no data
in new invoice -> configuration name, contact name , unit currency, enter description (font is wrong)

remove junk characters (chinese language remove programmatically).

**Comment by dweep119** [comment]
Issue is solve but there is one field **_Product_line_**, that field data doesn't come because we have to discuss which data we have to display in that field.
