### ISSUE TITLE
invoice and customer - meaningful headers

### ISSUE THREAD

**Issue by emp005169** [FlowzPlatform/crmadmin-cum-finance#68]
give meaningful name to headers in invoice, customer and relationship tables.

like, Customer Name instead of just Name
Due Date instead of just Date

**Comment by h1995** [comment]
changed headers

**Comment by emp005169** [comment]
Customer Name instead of just Name - still not corrected in list customer and list relationship tables.
remove issupplier and iscustomer columns also.

**Comment by h1995** [comment]
Done.
But, on new relationship list Dweep is working so when his branch is merged you can see the Customer Name insted of Name.

**Comment by emp005169** [comment]
the first letter (home) is small on dashboard page/landing page.

**Comment by dweep119** [comment]
Done.
