### ISSUE TITLE
Invoice view/download Issues

### ISSUE THREAD

**Issue by emp005169** [FlowzPlatform/crmadmin-cum-finance#72]
Invoice format (download and view) has following issues:

1. date format is wrong. keep it only date without hours and minutes (00:00...)
2. take company name, logo and address (from: part) through settings.
3. remove payment method and payment (stripe) details
4. final field (total) to be kept as (total due) and value as 'Due Amount' in default currency.

**Comment by h1995** [comment]
done

**Comment by emp005169** [comment]
1. Invoice tax is not coming properly.It should be amount (tax amount) instead of percentage. check and correct.
2. On click of download invoice, loader should be visible till invoice is shown.

**Comment by h1995** [comment]
done
