### ISSUE TITLE
My account functionalities

### ISSUE THREAD

**Issue by emp005169** [FlowzPlatform/crmadmin-cum-finance#99]
add user's 'my account' functionalities for all websites.
-orderlist
-RFQ (vue component email thread)
-Product listing
-user details (activate/deactivate, change password)
-address book
-Bills (make payment)

**Comment by dweep119** [comment]
In _**My-account**_ Section,
orderlist,
RFQ,
user details (change password)
address book (listing) 
is **_done_**.
